# Generated by Django 4.2.4 on 2023-08-28 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto_Cadastrados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, db_column='Foto', null=True, upload_to='')),
                ('id_pessoa', models.ForeignKey(blank=True, db_column='Id_Pessoa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.cadastros')),
            ],
        ),
    ]
