# Generated by Django 4.2.4 on 2023-08-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_foto_cadastrados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=250, null=True)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=254, null=True)),
                ('mensagem', models.TextField(blank=True, db_column='Mensagem', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cadastros',
            name='data_nascimento',
            field=models.CharField(blank=True, db_column='Data_Nascimento', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='foto_cadastrados',
            name='foto',
            field=models.ImageField(blank=True, db_column='Foto', null=True, upload_to='fotos'),
        ),
    ]
