# Generated by Django 4.2.4 on 2023-08-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_foto_cadastrados_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainEmpresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.TextField(blank=True, db_column='CNPJ', null=True)),
                ('nome', models.TextField(blank=True, db_column='Nome', null=True)),
                ('endereço', models.TextField(blank=True, db_column='Endereço', null=True)),
                ('telefone', models.TextField(blank=True, db_column='Telefone', null=True)),
                ('email', models.TextField(blank=True, db_column='Email', null=True)),
            ],
            options={
                'db_table': 'main_empresas',
                'managed': False,
            },
        ),
    ]
